### ISSUE TITLE
Dependency issue: msmetaenhancer

### ISSUE THREAD

**Issue by jennaj** [usegalaxy-eu/infrastructure-playbook#1143]
tool_id: toolshed.g2.bx.psu.edu/repos/recetox/msmetaenhancer/msmetaenhancer/0.3.0+galaxy3

Job logs report the following
> -> ServiceNotAvailable - PubChem: inchi -> isomeric_smiles:
Service PubChem not available.

Cannot be reported since not a red failed result. 

Impacting the attribute discovery rates.

Not reproducible at Galaxy UMSA, seems to be actual external resource query "bug".

Paired testing histories:

* https://usegalaxy.eu/u/jenj/h/copy-of-msme-bug-report-ghelp-11821-bug-with-external-source-query-at-eu
* https://umsa.cerit-sc.cz/u/jen-galaxyproject/h/imported-galaxy-bug-report-umsa-ghelp-11821-bug-with-external-source-query-at-eu

Reported at: https://help.galaxyproject.org/t/msmetaenhancer-cant-reach-services-if-running-on-usegalaxy-eu/11821/

**Comment by hechth** [comment]
@bgruening we've also tested the BridgeDB service which gives a similar error - so it looks like we can't reach any webservice, which would suggest that the outgoing requests from the tool are somehow blocked by Galaxy?

**Comment by sanjaysrikakulam** [comment]
@hechth, I have updated the firewall of our compute cluster. Please try once again and let us know whether it works.

**Comment by zargham-ahmad** [comment]
@sanjaysrikakulam tested it, getting the same error. History: https://usegalaxy.eu/u/134b359e2e5e4dff852727053d4bef1d/h/test-msme

**Comment by sanjaysrikakulam** [comment]
Please tell me which external service this tool is trying to communicate to and which port it is trying to use. I have reconfigured our firewall to allow an extensive port range (above >1024) and several subnets of NCBI. 

I am unsure of what is still missing.

**Comment by sanjaysrikakulam** [comment]
From the tools GitHub repo, I see the list of external services this tool talks to,

> MSMetaEnhancer is a tool used for .msp file annotation. It adds metadata like SMILES, InChI, and CAS number fetched from the following services: [CIR](https://cactus.nci.nih.gov/chemical/structure_documentation), [CTS](https://cts.fiehnlab.ucdavis.edu/), [PubChem](https://pubchem.ncbi.nlm.nih.gov/), [IDSM](https://idsm.elixir-czech.cz/), and [BridgeDb](https://bridgedb.github.io/)

Based on the metadata issues reported in the above-shared history, I see it has issues with PubChem and IDSM,

> https://usegalaxy.eu/u/134b359e2e5e4dff852727053d4bef1d/h/test-msme

However, I can reach both of them through `curl` via our compute cluster. So, our firewall seems fine.

**Comment by sanjaysrikakulam** [comment]
OK, ports 80 and 443 egress are enabled by default. I will do some more tests and see what's going on.

**Comment by hechth** [comment]
@sanjaysrikakulam did you find something? I just reran the jobs and it still has the same problems.

We don't see this on our Galaxy instance - would it help you if we arranged a call and I could give you some insight into our deployment?

**Comment by sanjaysrikakulam** [comment]
@hechth Unfortunately, I did not find time to do further tests. I will run the tool locally this week to see what is happening and get back to you. We can then schedule a meeting to go over your setup.

**Comment by sanjaysrikakulam** [comment]
Here are my debugging results

1. DNS check:

```
~$ nslookup pubchem.ncbi.nlm.nih.gov
Server:         132.230.200.200
Address:        132.230.200.200#53

Non-authoritative answer:
pubchem.ncbi.nlm.nih.gov        canonical name = www.wip.ncbi.nlm.nih.gov.
Name:   www.wip.ncbi.nlm.nih.gov
Address: 130.14.29.110
Name:   www.wip.ncbi.nlm.nih.gov
Address: 2607:f220:41e:4290::110
```
So, there are no issues with the DNS

2. CURL check

```
$ curl https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/name/Methane/JSON
{
  "PC_Compounds": [
    {
      "id": {
        "id": {
          "cid": 297
        }
      },
      "atoms": {
        "aid": [
          1,
          2,
          3,
          4,
          5
        ],
        "element": [
          6,
          1,
          1,
          1,
          1
        ]
      },
      "bonds": {
        "aid1": [
          1,
          1,
          1,
          1
        ],
        "aid2": [
          2,
          3,
          4,
          5
        ],
        "order": [
          1,
          1,
          1,
          1
        ]
      },
      "coords": [
        {
          "type": [
            1,
            5,
            255
          ],
          "aid": [
            1,
            2,
            3,
            4,
            5
          ],
          "conformers": [
            {
              "x": [
                2.5369,
                3.0739,
                2,
                2.2269,
                2.8469
              ],
              "y": [
                0,
                0.31,
                -0.31,
                0.5369,
                -0.5369
              ]
            }
          ]
        }
      ],
      "charge": 0,
      "props": [
        {
          "urn": {
            "label": "Compound",
            "name": "Canonicalized",
            "datatype": 5,
            "release": "2021.10.14"
          },
          "value": {
            "ival": 1
          }
        },
        {
          "urn": {
            "label": "Compound Complexity",
            "datatype": 7,
            "implementation": "E_COMPLEXITY",
            "version": "3.4.8.18",
            "software": "Cactvs",
            "source": "Xemistry GmbH",
            "release": "2021.10.14"
          },
          "value": {
            "fval": 0
          }
        },
        {
          "urn": {
            "label": "Count",
            "name": "Hydrogen Bond Acceptor",
            "datatype": 5,
            "implementation": "E_NHACCEPTORS",
            "version": "3.4.8.18",
            "software": "Cactvs",
            "source": "Xemistry GmbH",
            "release": "2021.10.14"
          },
          "value": {
            "ival": 0
          }
        },
        {
          "urn": {
            "label": "Count",
            "name": "Hydrogen Bond Donor",
            "datatype": 5,
            "implementation": "E_NHDONORS",
            "version": "3.4.8.18",
            "software": "Cactvs",
            "source": "Xemistry GmbH",
            "release": "2021.10.14"
          },
          "value": {
            "ival": 0
          }
        },
        {
          "urn": {
            "label": "Count",
            "name": "Rotatable Bond",
            "datatype": 5,
            "implementation": "E_NROTBONDS",
            "version": "3.4.8.18",
            "software": "Cactvs",
            "source": "Xemistry GmbH",
            "release": "2021.10.14"
          },
          "value": {
            "ival": 0
          }
        },
        {
          "urn": {
            "label": "Fingerprint",
            "name": "SubStructure Keys",
            "datatype": 16,
            "parameters": "extended 2",
            "implementation": "E_SCREEN",
            "version": "3.4.8.18",
            "software": "Cactvs",
            "source": "Xemistry GmbH",
            "release": "2021.10.14"
          },
          "value": {
            "binary": "00000371800000000000000000000000000000000000000000000000000000000000000000000010000000000000000000000200000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000"
          }
        },
        {
          "urn": {
            "label": "IUPAC Name",
            "name": "Allowed",
            "datatype": 1,
            "version": "2.7.0",
            "software": "Lexichem TK",
            "source": "OpenEye Scientific Software",
            "release": "2021.10.14"
          },
          "value": {
            "sval": "methane"
          }
        },
        {
          "urn": {
            "label": "IUPAC Name",
            "name": "CAS-like Style",
            "datatype": 1,
            "version": "2.7.0",
            "software": "Lexichem TK",
            "source": "OpenEye Scientific Software",
            "release": "2021.10.14"
          },
          "value": {
            "sval": "methane"
          }
        },
        {
          "urn": {
            "label": "IUPAC Name",
            "name": "Markup",
            "datatype": 1,
            "version": "2.7.0",
            "software": "Lexichem TK",
            "source": "OpenEye Scientific Software",
            "release": "2021.10.14"
          },
          "value": {
            "sval": "methane"
          }
        },
        {
          "urn": {
            "label": "IUPAC Name",
            "name": "Preferred",
            "datatype": 1,
            "version": "2.7.0",
            "software": "Lexichem TK",
            "source": "OpenEye Scientific Software",
            "release": "2021.10.14"
          },
          "value": {
            "sval": "methane"
          }
        },
        {
          "urn": {
            "label": "IUPAC Name",
            "name": "Systematic",
            "datatype": 1,
            "version": "2.7.0",
            "software": "Lexichem TK",
            "source": "OpenEye Scientific Software",
            "release": "2021.10.14"
          },
          "value": {
            "sval": "methane"
          }
        },
        {
          "urn": {
            "label": "IUPAC Name",
            "name": "Traditional",
            "datatype": 1,
            "version": "2.7.0",
            "software": "Lexichem TK",
            "source": "OpenEye Scientific Software",
            "release": "2021.10.14"
          },
          "value": {
            "sval": "methane"
          }
        },
        {
          "urn": {
            "label": "InChI",
            "name": "Standard",
            "datatype": 1,
            "version": "1.0.6",
            "software": "InChI",
            "source": "iupac.org",
            "release": "2021.10.14"
          },
          "value": {
            "sval": "InChI=1S/CH4/h1H4"
          }
        },
        {
          "urn": {
            "label": "InChIKey",
            "name": "Standard",
            "datatype": 1,
            "version": "1.0.6",
            "software": "InChI",
            "source": "iupac.org",
            "release": "2021.10.14"
          },
          "value": {
            "sval": "VNWKTOKETHGBQD-UHFFFAOYSA-N"
          }
        },
        {
          "urn": {
            "label": "Log P",
            "name": "XLogP3-AA",
            "datatype": 7,
            "version": "3.0",
            "source": "sioc-ccbg.ac.cn",
            "release": "2021.10.14"
          },
          "value": {
            "fval": 0.6
          }
        },
        {
          "urn": {
            "label": "Mass",
            "name": "Exact",
            "datatype": 1,
            "version": "2.2",
            "software": "PubChem",
            "source": "ncbi.nlm.nih.gov",
            "release": "2021.10.14"
          },
          "value": {
            "sval": "16.0313001276"
          }
        },
        {
          "urn": {
            "label": "Molecular Formula",
            "datatype": 1,
            "version": "2.2",
            "software": "PubChem",
            "source": "ncbi.nlm.nih.gov",
            "release": "2021.10.14"
          },
          "value": {
            "sval": "CH4"
          }
        },
        {
          "urn": {
            "label": "Molecular Weight",
            "datatype": 1,
            "version": "2.2",
            "software": "PubChem",
            "source": "ncbi.nlm.nih.gov",
            "release": "2021.10.14"
          },
          "value": {
            "sval": "16.043"
          }
        },
        {
          "urn": {
            "label": "SMILES",
            "name": "Canonical",
            "datatype": 1,
            "version": "2.3.0",
            "software": "OEChem",
            "source": "OpenEye Scientific Software",
            "release": "2021.10.14"
          },
          "value": {
            "sval": "C"
          }
        },
        {
          "urn": {
            "label": "SMILES",
            "name": "Isomeric",
            "datatype": 1,
            "version": "2.3.0",
            "software": "OEChem",
            "source": "OpenEye Scientific Software",
            "release": "2021.10.14"
          },
          "value": {
            "sval": "C"
          }
        },
        {
          "urn": {
            "label": "Topological",
            "name": "Polar Surface Area",
            "datatype": 7,
            "implementation": "E_TPSA",
            "version": "3.4.8.18",
            "software": "Cactvs",
            "source": "Xemistry GmbH",
            "release": "2021.10.14"
          },
          "value": {
            "fval": 0
          }
        },
        {
          "urn": {
            "label": "Weight",
            "name": "MonoIsotopic",
            "datatype": 1,
            "version": "2.2",
            "software": "PubChem",
            "source": "ncbi.nlm.nih.gov",
            "release": "2021.10.14"
          },
          "value": {
            "sval": "16.0313001276"
          }
        }
      ],
      "count": {
        "heavy_atom": 1,
        "atom_chiral": 0,
        "atom_chiral_def": 0,
        "atom_chiral_undef": 0,
        "bond_chiral": 0,
        "bond_chiral_def": 0,
        "bond_chiral_undef": 0,
        "isotope_atom": 0,
        "covalent_unit": 1,
        "tautomers": -1
      }
    }
  ]
}
```
The CURL URL was populated based on [MSMetaEnhancer](https://github.com/RECETOX/MSMetaEnhancer/blob/9b6eae21e23155c7f2eb8653b5209e096f0a0ee2/MSMetaEnhancer/libs/converters/web/PubChem.py#L91-L100). There does not seem to be a network or firewall-related issue, and this also shows that PubChem, for example, does not block our IPs.

3. Installed version on EU `msmetaenhancer | 0.3.0+galaxy4`
conda env packages list
```
Python 3.11.4
aiohttp 3.8.4
asyncstdlib 3.10.8
msmetaenhancer 0.3.0
requests  2.31.0
```

So, I tried the Python scripts below to test what is going on
Using `aiohttp`
```
import aiohttp
import asyncio

async def fetch_methane_data():
    url = "https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/name/Methane/JSON"
    
    async with aiohttp.ClientSession() as session:
        async with session.get(url) as response:
            if response.status == 200:
                data = await response.json()
                print(data)
            else:
                print(f"Failed to fetch data: {response.status}")

# To run the async function
asyncio.run(fetch_methane_data())

Traceback (most recent call last):
  File "/usr/local/tools/_conda/envs/__msmetaenhancer@0.3.0/lib/python3.11/site-packages/aiohttp/connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/tools/_conda/envs/__msmetaenhancer@0.3.0/lib/python3.11/asyncio/base_events.py", line 1085, in create_connection
    raise exceptions[0]
  File "/usr/local/tools/_conda/envs/__msmetaenhancer@0.3.0/lib/python3.11/asyncio/base_events.py", line 1069, in create_connection
    sock = await self._connect_sock(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/tools/_conda/envs/__msmetaenhancer@0.3.0/lib/python3.11/asyncio/base_events.py", line 973, in _connect_sock
    await self.sock_connect(sock, address)
  File "/usr/local/tools/_conda/envs/__msmetaenhancer@0.3.0/lib/python3.11/asyncio/selector_events.py", line 634, in sock_connect
    return await fut
           ^^^^^^^^^
  File "/usr/local/tools/_conda/envs/__msmetaenhancer@0.3.0/lib/python3.11/asyncio/selector_events.py", line 642, in _sock_connect
    sock.connect(address)
OSError: [Errno 101] Network is unreachable

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/tools/_conda/envs/__msmetaenhancer@0.3.0/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/local/tools/_conda/envs/__msmetaenhancer@0.3.0/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/tools/_conda/envs/__msmetaenhancer@0.3.0/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "<stdin>", line 5, in fetch_methane_data
  File "/usr/local/tools/_conda/envs/__msmetaenhancer@0.3.0/lib/python3.11/site-packages/aiohttp/client.py", line 1141, in __aenter__
    self._resp = await self._coro
                 ^^^^^^^^^^^^^^^^
  File "/usr/local/tools/_conda/envs/__msmetaenhancer@0.3.0/lib/python3.11/site-packages/aiohttp/client.py", line 536, in _request
    conn = await self._connector.connect(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/tools/_conda/envs/__msmetaenhancer@0.3.0/lib/python3.11/site-packages/aiohttp/connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/tools/_conda/envs/__msmetaenhancer@0.3.0/lib/python3.11/site-packages/aiohttp/connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/tools/_conda/envs/__msmetaenhancer@0.3.0/lib/python3.11/site-packages/aiohttp/connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "/usr/local/tools/_conda/envs/__msmetaenhancer@0.3.0/lib/python3.11/site-packages/aiohttp/connector.py", line 1175, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/tools/_conda/envs/__msmetaenhancer@0.3.0/lib/python3.11/site-packages/aiohttp/connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host pubchem.ncbi.nlm.nih.gov:443 ssl:default [Network is unreachable]
>>>
```

Tested the same with `requests` package instead of `aiohttp`.

```
import requests

url = "https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/name/Methane/JSON"
response = requests.get(url)
print(response.json())


{'PC_Compounds': [{'id': {'id': {'cid': 297}}, 'atoms': {'aid': [1, 2, 3, 4, 5], 'element': [6, 1, 1, 1, 1]}, 'bonds': {'aid1': [1, 1, 1, 1], 'aid2': [2, 3, 4, 5], 'order': [1, 1, 1, 1]}, 'coords': [{'type': [1, 5, 255], 'aid': [1, 2, 3, 4, 5], 'conformers': [{'x': [2.5369, 3.0739, 2, 2.2269, 2.8469], 'y': [0, 0.31, -0.31, 0.5369, -0.5369]}]}], 'charge': 0, 'props': [{'urn': {'label': 'Compound', 'name': 'Canonicalized', 'datatype': 5, 'release': '2021.10.14'}, 'value': {'ival': 1}}, {'urn': {'label': 'Compound Complexity', 'datatype': 7, 'implementation': 'E_COMPLEXITY', 'version': '3.4.8.18', 'software': 'Cactvs', 'source': 'Xemistry GmbH', 'release': '2021.10.14'}, 'value': {'fval': 0}}, {'urn': {'label': 'Count', 'name': 'Hydrogen Bond Acceptor', 'datatype': 5, 'implementation': 'E_NHACCEPTORS', 'version': '3.4.8.18', 'software': 'Cactvs', 'source': 'Xemistry GmbH', 'release': '2021.10.14'}, 'value': {'ival': 0}}, {'urn': {'label': 'Count', 'name': 'Hydrogen Bond Donor', 'datatype': 5, 'implementation': 'E_NHDONORS', 'version': '3.4.8.18', 'software': 'Cactvs', 'source': 'Xemistry GmbH', 'release': '2021.10.14'}, 'value': {'ival': 0}}, {'urn': {'label': 'Count', 'name': 'Rotatable Bond', 'datatype': 5, 'implementation': 'E_NROTBONDS', 'version': '3.4.8.18', 'software': 'Cactvs', 'source': 'Xemistry GmbH', 'release': '2021.10.14'}, 'value': {'ival': 0}}, {'urn': {'label': 'Fingerprint', 'name': 'SubStructure Keys', 'datatype': 16, 'parameters': 'extended 2', 'implementation': 'E_SCREEN', 'version': '3.4.8.18', 'software': 'Cactvs', 'source': 'Xemistry GmbH', 'release': '2021.10.14'}, 'value': {'binary': '00000371800000000000000000000000000000000000000000000000000000000000000000000010000000000000000000000200000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000'}}, {'urn': {'label': 'IUPAC Name', 'name': 'Allowed', 'datatype': 1, 'version': '2.7.0', 'software': 'Lexichem TK', 'source': 'OpenEye Scientific Software', 'release': '2021.10.14'}, 'value': {'sval': 'methane'}}, {'urn': {'label': 'IUPAC Name', 'name': 'CAS-like Style', 'datatype': 1, 'version': '2.7.0', 'software': 'Lexichem TK', 'source': 'OpenEye Scientific Software', 'release': '2021.10.14'}, 'value': {'sval': 'methane'}}, {'urn': {'label': 'IUPAC Name', 'name': 'Markup', 'datatype': 1, 'version': '2.7.0', 'software': 'Lexichem TK', 'source': 'OpenEye Scientific Software', 'release': '2021.10.14'}, 'value': {'sval': 'methane'}}, {'urn': {'label': 'IUPAC Name', 'name': 'Preferred', 'datatype': 1, 'version': '2.7.0', 'software': 'Lexichem TK', 'source': 'OpenEye Scientific Software', 'release': '2021.10.14'}, 'value': {'sval': 'methane'}}, {'urn': {'label': 'IUPAC Name', 'name': 'Systematic', 'datatype': 1, 'version': '2.7.0', 'software': 'Lexichem TK', 'source': 'OpenEye Scientific Software', 'release': '2021.10.14'}, 'value': {'sval': 'methane'}}, {'urn': {'label': 'IUPAC Name', 'name': 'Traditional', 'datatype': 1, 'version': '2.7.0', 'software': 'Lexichem TK', 'source': 'OpenEye Scientific Software', 'release': '2021.10.14'}, 'value': {'sval': 'methane'}}, {'urn': {'label': 'InChI', 'name': 'Standard', 'datatype': 1, 'version': '1.0.6', 'software': 'InChI', 'source': 'iupac.org', 'release': '2021.10.14'}, 'value': {'sval': 'InChI=1S/CH4/h1H4'}}, {'urn': {'label': 'InChIKey', 'name': 'Standard', 'datatype': 1, 'version': '1.0.6', 'software': 'InChI', 'source': 'iupac.org', 'release': '2021.10.14'}, 'value': {'sval': 'VNWKTOKETHGBQD-UHFFFAOYSA-N'}}, {'urn': {'label': 'Log P', 'name': 'XLogP3-AA', 'datatype': 7, 'version': '3.0', 'source': 'sioc-ccbg.ac.cn', 'release': '2021.10.14'}, 'value': {'fval': 0.6}}, {'urn': {'label': 'Mass', 'name': 'Exact', 'datatype': 1, 'version': '2.2', 'software': 'PubChem', 'source': 'ncbi.nlm.nih.gov', 'release': '2021.10.14'}, 'value': {'sval': '16.0313001276'}}, {'urn': {'label': 'Molecular Formula', 'datatype': 1, 'version': '2.2', 'software': 'PubChem', 'source': 'ncbi.nlm.nih.gov', 'release': '2021.10.14'}, 'value': {'sval': 'CH4'}}, {'urn': {'label': 'Molecular Weight', 'datatype': 1, 'version': '2.2', 'software': 'PubChem', 'source': 'ncbi.nlm.nih.gov', 'release': '2021.10.14'}, 'value': {'sval': '16.043'}}, {'urn': {'label': 'SMILES', 'name': 'Canonical', 'datatype': 1, 'version': '2.3.0', 'software': 'OEChem', 'source': 'OpenEye Scientific Software', 'release': '2021.10.14'}, 'value': {'sval': 'C'}}, {'urn': {'label': 'SMILES', 'name': 'Isomeric', 'datatype': 1, 'version': '2.3.0', 'software': 'OEChem', 'source': 'OpenEye Scientific Software', 'release': '2021.10.14'}, 'value': {'sval': 'C'}}, {'urn': {'label': 'Topological', 'name': 'Polar Surface Area', 'datatype': 7, 'implementation': 'E_TPSA', 'version': '3.4.8.18', 'software': 'Cactvs', 'source': 'Xemistry GmbH', 'release': '2021.10.14'}, 'value': {'fval': 0}}, {'urn': {'label': 'Weight', 'name': 'MonoIsotopic', 'datatype': 1, 'version': '2.2', 'software': 'PubChem', 'source': 'ncbi.nlm.nih.gov', 'release': '2021.10.14'}, 'value': {'sval': '16.0313001276'}}], 'count': {'heavy_atom': 1, 'atom_chiral': 0, 'atom_chiral_def': 0, 'atom_chiral_undef': 0, 'bond_chiral': 0, 'bond_chiral_def': 0, 'bond_chiral_undef': 0, 'isotope_atom': 0, 'covalent_unit': 1, 'tautomers': -1}}]}
>>>
```
I repeated these tests on our head node and a compute worker node. I used the same conda environment (one that Galaxy creates while installing the tool). Looks like `aiohttp` is the issue.

4. To test if it is `aiohttp`, I installed Miniconda on a worker node (where I tested the above) and created a new environment as given in the ReadMe of the tool [here](https://github.com/RECETOX/MSMetaEnhancer?tab=readme-ov-file#installation). I reran both the above scripts, and they both work fine. 

``` bash
# install MSMetaEnhancer in a new virtual environment to avoid dependency clashes
conda create --name MSMetaEnhancer python=3.9
conda activate MSMetaEnhancer
conda install --channel bioconda --channel conda-forge MSMetaEnhancer
```

5. Next, tested it with Python 3.11.4 (like the one in the env that Galaxy created when installing this tool)

``` bash
# install MSMetaEnhancer in a new virtual environment to avoid dependency clashes
conda create --name msmeta python=3.11.4
conda activate msmeta
conda install --channel bioconda --channel conda-forge MSMetaEnhancer
```
Reran both the above scripts and both work fine.

**Conclusion**
The issue seems to be with the package `aiohttp`  version `3.8.4`. So, I suggest releasing a new version of this tool, `MSMetaEnhancer`. We will then install the latest version, and you can test it and hopefully this will get resolved.

**Comment by hechth** [comment]
@sanjaysrikakulam this is great news and thanks so much for the detailed testing and information! I'll update the package deps to a newer version of aiohttp (if possible) and we will release a new version. I will then test the new version and see if the error persists.

**Comment by sanjaysrikakulam** [comment]
@hechth Cool, thanks!

**Comment by hechth** [comment]
I've just seen that we already released a new version 0.4 with aiohttp 3.9 and higher, but it isn't on usegalaxy.eu and somehow also not on the toolshed

**Comment by sanjaysrikakulam** [comment]
Yup, sorry, I should have explicitly mentioned that. The latest version is not in the ToolShed, which is what I meant by releasing a new version of the tool.

**Comment by hechth** [comment]
I will check the tool on Monday, then there shuld be the latest update

**Comment by hechth** [comment]
This seems to be working now - thanks for finding this out and investigating!

**Comment by sanjaysrikakulam** [comment]
@hechth cool; thanks for updating.

**Comment by sanjaysrikakulam** [comment]
I can confirm that the tool works with the latest version, `0.4.0`.
